version: '3.8'

services:
  # SpacetimeDB container
  spacetimedb:
    image: clockworklabs/spacetime:latest
    container_name: spacetimedb
    ports:
      - "3000:3000"  # Web interface
      - "4000:4000"  # Client API port
    volumes:
      - spacetime-data:/var/lib/spacetime
    command: start
    networks:
      - spacetime-network
    restart: unless-stopped

  # Rust server module
  rust-server:
    build:
      context: ./game_server_module
      dockerfile: Dockerfile.server
    container_name: spacetime-rust-server
    volumes:
      - ./game_server_module:/app
    depends_on:
      - spacetimedb
    environment:
      - SPACETIME_HOST=spacetimedb
      - SPACETIME_PORT=3000
    networks:
      - spacetime-network
    restart: unless-stopped

  # Python Quart client application
  client:
    build:
      context: ./client_game_server
      dockerfile: Dockerfile.client
    container_name: spacetime-client
    volumes:
      - ./client_game_server:/app
    ports:
      - "8080:8080"  # Map host 8080 to Quart's port 8080
    depends_on:
      - spacetimedb
      - rust-server
    environment:
      - SPACETIME_HOST=spacetimedb
      - SPACETIME_PORT=4000
    networks:
      - spacetime-network
    restart: unless-stopped

networks:
  spacetime-network:
    driver: bridge

volumes:
  spacetime-data: