services:
  # SpacetimeDB container
  spacetimedb:
    image: clockworklabs/spacetime
    pull_policy: always
    command: start
    ports:
      - "3000:3000"
    restart: "no"

# Rust server module - runs once and exits
  rust-server:
    build:
      context: ./game_server_module
      dockerfile: Dockerfile.server
    container_name: spacetime-rust-server
    volumes:
      - ./game_server_module:/app
    depends_on:
      - spacetimedb
    environment:
      - SPACETIME_HOST=spacetimedb
      - SPACETIME_PORT=3000
    networks:
      - spacetime-network
    restart: "no"  # Do not restart when finished
    # Alternative approach if you need the container to stop after execution:
    # command: sh -c "your_init_commands && exit 0"

  # Python Quart client application
  client:
    build:
      context: ./client_game_server
      dockerfile: Dockerfile.client
    container_name: spacetime-client
    volumes:
      - ./client_game_server:/app
    ports:
      - "8080:8080"  # Map host 8080 to Quart's port 8080
    depends_on:
      - spacetimedb
      - rust-server
    environment:
      - SPACETIME_HOST=spacetimedb
      - SPACETIME_PORT=4000
    networks:
      - spacetime-network
    restart: unless-stopped

networks:
  spacetime-network:
    driver: bridge

volumes:
  spacetime-data: