[package]
name = "spacetime-game-server"
version = "0.1.0"
edition = "2021"

[dependencies]
spacetimedb = "0.8.0"
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0"

[lib]
crate-type = ["cdylib"]